# Generated by Django 4.1.7 on 2023-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_title", models.CharField(max_length=20)),
                ("collection_description", models.CharField(max_length=100)),
                ("movie_titles", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("title", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=10)),
                ("genres", models.CharField(max_length=10)),
                ("uuid", models.IntegerField()),
            ],
        ),
    ]
