# Generated by Django 4.1.7 on 2023-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webAPIs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="movie_titles",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movies",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movies", name="genres", field=models.CharField(max_length=30),
        ),
    ]
